using System.Reflection;

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("AutoGenerated")]
[assembly: AssemblyDescription("Auto generated assemblies from XsdToObject")]
[assembly: AssemblyProduct("AutoGenerated.Properties")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]
